--Creating a new user for dbt to run dbt models using Key-Pair Auth method

USE ROLE ACCOUNTADMIN;
GRANT CREATE ROLE ON ACCOUNT TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
CREATE ROLE IF NOT EXISTS DBT_ROLE;

CREATE DATABASE IF NOT EXISTS TEST_DB;
CREATE SCHEMA IF NOT EXISTS DBT;

GRANT USAGE ON DATABASE TEST_DB TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA DBT TO ROLE DBT_ROLE;
GRANT
INSERT,
    REFERENCES,
SELECT,
    TRUNCATE,
UPDATE
    ON FUTURE TABLES IN SCHEMA DBT TO ROLE DBT_ROLE;

USE ROLE ACCOUNTADMIN;
CREATE USER IF NOT EXISTS DBT_USER 
LOGIN_NAME = DBT_USER 
DISPLAY_NAME = DBT_USER
RSA_PUBLIC_KEY = '<YOUR_PUBLIC_KEY_WITHOUT_DASHED_COMMENTS>' /* E.g., MIIBI.... */ 
COMMENT = 'Service account for the DBT User';

--CHECK THE USER CREATION:
DESC USER DBT_USER;

USE ROLE SYSADMIN;
GRANT ROLE DBT_ROLE TO USER DBT_USER;