--Creating a new user for dbt to run dbt models using Key-Pair Auth method

USE ROLE ACCOUNTADMIN;
GRANT CREATE ROLE ON ACCOUNT TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
CREATE ROLE IF NOT EXISTS DBT_ROLE;

USE ROLE ACCOUNTADMIN;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN;

GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE DBT_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DBT_ROLE;

USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS TEST_DB;
CREATE SCHEMA IF NOT EXISTS DBT;

GRANT USAGE ON DATABASE TEST_DB TO ROLE DBT_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE TEST_DB TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA TEST_DB.DBT TO ROLE DBT_ROLE;

GRANT INSERT, REFERENCES, SELECT, TRUNCATE, UPDATE ON ALL TABLES IN SCHEMA DBT TO ROLE DBT_ROLE;
GRANT INSERT, REFERENCES, SELECT, TRUNCATE, UPDATE ON FUTURE TABLES IN SCHEMA DBT TO ROLE DBT_ROLE;

USE ROLE ACCOUNTADMIN;
CREATE USER IF NOT EXISTS DBT_USER 
LOGIN_NAME = DBT_USER 
DISPLAY_NAME = DBT_USER
RSA_PUBLIC_KEY = '<YOUR_PUBLIC_KEY_WITHOUT_DASHED_COMMENTS>' /* E.g., MIIBI.... */ 
COMMENT = 'Service account for the DBT User';

--CHECK THE USER CREATION:
DESC USER DBT_USER;

USE ROLE SYSADMIN;
GRANT ROLE DBT_ROLE TO USER DBT_USER;

--CREATING A TABLE TO CAPTURE FAILED QUERIES BY DBT USER FOR DEBUGGING PURPOSES

USE ROLE SYSADMIN;

CREATE SCHEMA DBT_LOGS;
CREATE TABLE IF NOT EXISTS DBT_REDACTED_QUERIES
(
    USER_EXECUTED STRING,
    START_TS Timestamp_LTZ,
    END_TS Timestamp_LTZ,
    QUERY_TEXT STRING,
    ERROR_CODE STRING,
    ERROR_TEXT STRING
);

GRANT USAGE ON SCHEMA TO ROLE DBT_ROLE;
GRANT SELECT, INSERT, TRUNCATE, DELETE, UPDATE, REFERENCES ON ALL TABLES IN SCHEMA DBT_LOGS TO ROLE DBT_ROLE;

--CREATING A TABLE TO STORE REDACTED QUERIES THAT WERE RAN BY A SERVICE ACCOUNT

USE ROLE ACCOUNTADMIN;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE SYSADMIN;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE DBT_ROLE;

USE ROLE SYSADMIN;

CREATE SCHEMA DBT_LOGS;
CREATE TABLE IF NOT EXISTS TEST_DB.DBT_LOGS.DBT_REDACTED_QUERIES
(
    QUERY_ID STRING,
    USER_EXECUTED STRING,
    START_TS Timestamp_LTZ,
    END_TS Timestamp_LTZ,
    QUERY_TEXT STRING,
    ERROR_CODE STRING,
    ERROR_TEXT STRING
);


USE ROLE SYSADMIN;
GRANT USAGE ON SCHEMA TEST_DB.DBT_LOGS TO ROLE DBT_ROLE;
GRANT SELECT, INSERT, TRUNCATE, DELETE, UPDATE, REFERENCES ON ALL TABLES IN SCHEMA DBT_LOGS TO ROLE DBT_ROLE;