{{ config(schema="admin") }}

WITH cte_rap AS(
    SELECT 'PULP_EVICTION_DENTAL_OFFICE' AS ACCOUNT_NAME
    , 'NEW ZEALAND' AS ALLOWED_COUNTRY
    UNION ALL
    SELECT 'PULP_EVICTION_DENTAL_OFFICE', 'AUSTRALIA'
    UNION ALL
    SELECT 'PULP_EVICTION_DENTAL_OFFICE', 'NETHERLANDS'
)

SELECT * FROM cte_rap